version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node@3.0.0
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: npm run build:js
      - run: npm publish
  test:
    docker:
      - image: circleci/node@3.0.0
    steps:
      - checkout
      - run: echo "this is the test job"
      - run: npm run test:ci

workflows:
  build_and_test:
    jobs:
      - test
      - build
