version: 2.1

jobs:
  test_build_and_publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
        name: Installing dependencies
        command: npm i
       - run:
        name: Running tests
        command: npm run test:ci
      - run:
        name: Building dist and types directory
        command: npm run build:js
      - run:
        name: Authenticate with registry
        command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
        name: Publishing to npm registry
        command: npm publish
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
        name: Installing dependencies
        command: npm i
      

workflows:
  build_and_test:
    jobs:
      - test_build_and_publish
