version: 2.1

jobs:
  build_and_publish:
    docker:
      - image: node
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: npm i
      - run: npm run build:js
      - run: npm publish
  test:
    docker:
      - image: node
    steps:
      - checkout
      - run: echo "this is the test job"
      - run: npm i
      - run: npm run test:ci

workflows:
  build_and_test:
    jobs:
      - test
      - build_and_publish
