version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:10
    environment:
      HUSKY: 0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: yarn install --ignore-scripts
      - run:
          name: Running tests
          command: yarn test:ci
  build:
    docker:
      - image: circleci/node:10
    environment:
      HUSKY: 0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: yarn install --ignore-scripts
      - run:
          name: building dist and types directories
          command: yarn build:js
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Check if can publish to npm
          command: can-npm-publish --verbose
  build_and_deploy:
    docker:
      - image: circleci/node:10
    environment:
      HUSKY: 0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: yarn install --ignore-scripts
      - run:
          name: building dist and types directories
          command: yarn build:js
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Check if can publish to npm
          command: can-npm-publish --verbose
      - run:
          name: Publish package
          command: npm publish

workflows:
  build_and_test:
    jobs:
      - test
      - build:
          filters:
            branches:
              ignore:
                - master
          requires: test
      - build_and_deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
